name: lint

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-python@v2
      - uses: actions/setup-ruby@v1
      - uses: pre-commit/action@v2.0.0
